/** A standalone local inspector of the offline experiment's accepted equipment edits. */
export function inspector(runs: unknown[]): string {
	const data = JSON.stringify(runs).replace(/</g, "\\u003c");
	return `<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Magic circuit experiments</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#f5f3ed;color:#242b28;font:15px/1.5 system-ui,sans-serif}header{padding:28px 32px;background:#183c32;color:#faf9f5}h1{font-size:25px;margin:0 0 6px}header p{margin:0;color:#cbd9d1}main{max-width:1280px;margin:auto;padding:24px}button,select,input{font:inherit}select{padding:8px;border:1px solid #b8c7bd;border-radius:6px;background:white}nav{display:flex;gap:18px;align-items:center;flex-wrap:wrap;margin-bottom:20px}.layout{display:grid;grid-template-columns:300px 1fr;gap:20px}.timeline{max-height:76vh;overflow:auto;background:#fff;border:1px solid #d9ded7;border-radius:8px;padding:8px}.timeline button{display:block;width:100%;text-align:left;border:0;border-radius:5px;padding:9px 11px;background:transparent;cursor:pointer}.timeline button:hover{background:#edf3ee}.timeline button.active{background:#d8e8da}.timeline small{display:block;color:#597065}section{background:#fff;border:1px solid #d9ded7;border-radius:8px;padding:20px;margin-bottom:16px}h2{font-size:17px;margin:0 0 12px}h3{font-size:15px;margin:16px 0 6px}p{margin:6px 0}.muted{color:#62736a}.tag{display:inline-block;padding:2px 8px;border-radius:4px;background:#ecf1e9;font-size:12px;margin:0 5px 4px 0}.warn{background:#fff0cf}.good{background:#dceee0}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:9px 7px;border-bottom:1px solid #e4e8e1;vertical-align:top}th{font-size:12px;color:#62736a}pre{white-space:pre-wrap;word-break:break-word;font-size:12px;background:#f4f5f0;padding:14px;border-radius:6px}ol{padding-left:22px}li{margin:8px 0}.metrics{display:flex;gap:18px;flex-wrap:wrap}.metrics b{font-size:21px;display:block}.metrics span{font-size:12px;color:#62736a}#slider{flex:1;min-width:140px}@media(max-width:760px){.layout{grid-template-columns:1fr}.timeline{max-height:240px}header{padding:22px}main{padding:14px}}
</style>
<header><h1>Magic circuit experiments</h1><p>A real table with authored model doubles. Step through what the seat prepared, considered, and executed.</p></header>
<main><nav><label>Scenario <select id="scenario"></select></label><button id="previous">Previous</button><input id="slider" type="range" min="0"><button id="next">Next</button><span id="position"></span></nav>
<div class="layout"><aside class="timeline" id="timeline"></aside><div><section id="summary"></section><section id="board"></section><section id="draft"></section><section id="agenda"></section><section id="review"></section><details><summary>Recorded tools, position and equipment as JSON</summary><pre id="raw"></pre></details></div></div></main>
<script id="data" type="application/json">${data}</script>
<script>
const runs=JSON.parse(document.getElementById('data').textContent);let scenario=0,index=0;
const el=id=>document.getElementById(id);const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
el('scenario').innerHTML=runs.map((run,i)=>'<option value="'+i+'">'+esc(run.name)+'</option>').join('');
function title(entry){const tool=entry.tools?.[0];if(entry.note.startsWith('Executed'))return entry.note;if(!tool)return entry.note;if(tool.do==='review.answer')return 'Reviewed '+tool.task;if(tool.do==='draft.bind')return 'Bound '+tool.option;if(tool.do==='draft.ready')return 'Accepted readiness';if(tool.do==='draft.start')return 'Opened '+tool.recipe;if(tool.do==='draft.edit')return 'Revised remaining steps';if(tool.do==='recipe.put')return 'Prepared recipes and appointments';if(tool.do==='plan.request')return 'Requested strategy';if(tool.do==='task.cancel')return 'Retired '+tool.id;return entry.note;}
function render(){const run=runs[scenario],history=run.history,entry=history[index],work=entry.workspace;el('slider').max=history.length-1;el('slider').value=index;el('position').textContent=(index+1)+' / '+history.length;
el('timeline').innerHTML=history.map((e,i)=>'<button data-index="'+i+'" class="'+(i===index?'active':'')+'">'+esc(title(e))+'<small>Equipment '+e.workspace.revision+' · game clock '+e.clock+'</small></button>').join('');
el('summary').innerHTML='<h2>'+esc(title(entry))+'</h2><p>'+esc(work.objective||'A strategy request is waiting.')+'</p><div class="metrics"><div><b>'+run.plans+'</b><span>strategy calls in this experiment</span></div><div><b>'+run.batches+'</b><span>review batches</span></div><div><b>'+run.concernQuestions+'</b><span>individual concerns</span></div></div><p class="muted">These counts describe orchestration. The doubles do not establish playing strength or paid model cost.</p>'+(work.request?'<p class="tag warn">'+esc(work.request)+'</p>':'');
el('summary').innerHTML+='<p>'+esc(run.calls)+' classifier calls '+esc(run.callScope||'in the full game')+'. Inspecting seat '+esc(entry.seat)+'.</p>';
el('board').hidden=!entry.table;el('board').innerHTML=entry.table?'<h2>Public table at this checkpoint</h2><pre>'+esc(entry.table.join('\\n'))+'</pre>':'';
const draft=work.draft;el('draft').innerHTML='<h2>Action workbench</h2>'+(draft?'<p><b>'+esc(draft.label)+'</b></p><p>'+esc(draft.guidance)+'</p><span class="tag">'+esc(draft.status)+'</span><span class="tag">'+draft.next+' / '+draft.steps.length+' executed</span>'+(draft.bound?'<span class="tag">Bound '+esc(draft.bound)+'</span>':'')+'<ol>'+draft.steps.map((step,i)=>'<li><span class="tag '+(i<draft.next?'good':'')+'">'+(i<draft.next?'executed':i===draft.next?'next':'later')+'</span>'+esc(step.label)+'<div class="muted">'+esc(JSON.stringify(step.when))+'</div></li>').join('')+'</ol><h3>Reservations</h3>'+(draft.reserves.length?draft.reserves.map(r=>'<p>'+esc(r.object.id+'@'+r.object.incarnation+': '+r.purpose)+'</p>').join(''):'<p class="muted">No current reservations.</p>'):'<p class="muted">No draft has been adopted.</p>');
el('agenda').innerHTML='<h2>Agenda</h2><table><thead><tr><th>Check</th><th>Schedule</th><th>Progress</th></tr></thead><tbody>'+work.tasks.map(task=>'<tr><td>'+esc(task.label)+'</td><td>'+esc(JSON.stringify(task.when))+(task.after?'<br>After '+esc(task.after.task)+' has '+task.after.runs+' reviews':'')+'</td><td>'+task.runs.length+' / '+(task.times??'recurring')+(task.cancelled?'<br>cancelled':task.expired?'<br>expired':'')+'</td></tr>').join('')+'</tbody></table><h3>Labels</h3>'+work.labels.map(label=>'<p>'+esc(label.object.id+'@'+label.object.incarnation)+' <span class="tag">'+esc(label.role)+'</span>'+esc(label.purpose)+'</p>').join('');
const answer=entry.tools?.find(tool=>tool.do==='review.answer');el('review').innerHTML='<h2>Consideration record</h2>'+(answer?'<p>Each scoped object, concept, and label received its own disposition in one batch.</p><table><thead><tr><th>Subject and concern</th><th>Disposition</th></tr></thead><tbody>'+Object.entries(answer.answers).map(([key,value])=>'<tr><td>'+esc(JSON.parse(key).join(' · '))+'</td><td>'+esc(value)+'</td></tr>').join('')+'</tbody></table>':'<p class="muted">Select a review in the timeline to inspect its dispositions.</p>');
el('raw').textContent=JSON.stringify(entry,null,2);el('previous').disabled=index===0;el('next').disabled=index===history.length-1;}
el('scenario').onchange=event=>{scenario=Number(event.target.value);index=0;render()};el('slider').oninput=event=>{index=Number(event.target.value);render()};el('previous').onclick=()=>{index=Math.max(0,index-1);render()};el('next').onclick=()=>{index=Math.min(runs[scenario].history.length-1,index+1);render()};el('timeline').onclick=event=>{const button=event.target.closest('button');if(button){index=Number(button.dataset.index);render()}};render();
</script></html>`;
}
